name: Loon tests

on: [push]

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: "5.4.4"
    - name: Run tests
      run: lua tests/all.lua -o terminal
